using System.Text.Json;
using System.Text.Json.Serialization;

namespace NLWebNet.Models;

/// <summary>
/// Represents a single result item in an NLWeb response.
/// </summary>
public class NLWebResult
{
    /// <summary>
    /// The URL of the result item.
    /// </summary>
    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;

    /// <summary>
    /// The name or title of the result item.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// The site identifier this result belongs to.
    /// </summary>
    [JsonPropertyName("site")]
    public string Site { get; set; } = string.Empty;

    /// <summary>
    /// The relevance score of this result (typically 0.0 to 1.0).
    /// </summary>
    [JsonPropertyName("score")]
    public double Score { get; set; }

    /// <summary>
    /// A description of the result item, typically generated by an LLM.
    /// </summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// The item from the data store, encoded in JSON. This can be any JSON object
    /// representing the original data structure from the backend.
    /// </summary>
    [JsonPropertyName("schema_object")]
    public JsonElement? SchemaObject { get; set; }
}
